name: cgat-apps

on: [push, pull_request]

jobs:
  build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.11", "3.12"]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - name: Cache conda
        uses: actions/cache@v3
        env:
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('conda/environments/cgat-apps.yml') }}

      - name: Set installer URL and environment file
        id: set-installer-and-env
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            echo "installer-url=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-Linux-x86_64.sh" >> $GITHUB_ENV
            echo "env-file=conda/environments/cgat-apps.yml" >> $GITHUB_ENV
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            echo "installer-url=https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-arm64.sh" >> $GITHUB_ENV
            echo "env-file=conda/environments/cgat-apps-macos.yml" >> $GITHUB_ENV
          fi

      - uses: conda-incubator/setup-miniconda@v2
        with:
          installer-url: ${{ env.installer-url }}
          python-version: ${{ matrix.python-version }}
          channels: conda-forge, bioconda, defaults
          channel-priority: true
          activate-environment: cgat-a
          environment-file: ${{ env.env-file }}

      - name: Configure Conda Paths
        run: echo "/usr/share/miniconda3/condabin" >> $GITHUB_PATH

      - name: Show conda
        run: |
          conda info
          conda list
          
      - name: Debug Python Environment
        run: |
          python --version
          pip list
          openssl version
          
      - name: Apply macOS-specific patches
        if: matrix.os == 'macos-latest'
        run: |
          # Check if the patch needs to be applied
          if grep -q "Skip BigWig tests on macOS" tests/test_scripts.py; then
            echo "Patch already applied, skipping"
          else
            # Apply patch to skip BigWig tests on macOS
            patch -p1 < tests/skip_bigwig_tests_macos.patch
          fi
          
      - name: Test
        run: |
          pip install -e .
          pip install pytest
          pytest -v tests/test_style.py
          pytest -v tests/test_scripts.py
          pytest -v tests/test_import.py
